{
 "cells": [
  {
   "cell_type": "code",
   "execution_count": 4,
   "metadata": {},
   "outputs": [],
   "source": [
    "# !pip install suite2p"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 1,
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "loaded default ops\n",
      "objc[58093]: Class FIFinderSyncExtensionHost is implemented in both /System/Library/PrivateFrameworks/FinderKit.framework/Versions/A/FinderKit (0x7fff8f820210) and /System/Library/PrivateFrameworks/FileProvider.framework/OverrideBundles/FinderSyncCollaborationFileProviderOverride.bundle/Contents/MacOS/FinderSyncCollaborationFileProviderOverride (0x1c34652dc8). One of the two will be used. Which one is undefined.\n",
      "/Users/angueyraaristjm/Documents/LiImaging/TwoPhoton/ChAT_gCaMP6s_example/20190128_13_34_43\n",
      "Running suite2p!\n",
      "starting process\n",
      "{'data_path': ['/Users/angueyraaristjm/Documents/LiImaging/TwoPhoton/ChAT_gCaMP6s_example/20190128_13_34_43'], 'subfolders': [], 'save_path0': '/Users/angueyraaristjm/Documents/LiImaging/TwoPhoton/ChAT_gCaMP6s_example/20190128_13_34_43', 'fast_disk': '/Users/angueyraaristjm/Documents/LiImaging/TwoPhoton/ChAT_gCaMP6s_example/20190128_13_34_43'}\n",
      "\n",
      "ERROR: this is not a stat.npy file :( (needs stat[n][\"ypix\"]!)\n",
      "\n",
      "ERROR: this is not a stat.npy file :( (needs stat[n][\"ypix\"]!)\n",
      "/Users/angueyraaristjm/Documents/LiImaging/TwoPhoton/ChAT_gCaMP6s_example/20190128_13_34_43\n",
      "Running suite2p!\n",
      "starting process\n",
      "{'data_path': ['/Users/angueyraaristjm/Documents/LiImaging/TwoPhoton/ChAT_gCaMP6s_example/20190128_13_34_43', '/Users/angueyraaristjm/Documents/LiImaging/TwoPhoton/ChAT_gCaMP6s_example/20190128_13_34_43'], 'subfolders': [], 'save_path0': '/Users/angueyraaristjm/Documents/LiImaging/TwoPhoton/ChAT_gCaMP6s_example/20190128_13_34_43', 'fast_disk': '/Users/angueyraaristjm/Documents/LiImaging/TwoPhoton/ChAT_gCaMP6s_example/20190128_13_34_43'}\n",
      "/Users/angueyraaristjm/Documents/LiImaging/TwoPhoton/ChAT_gCaMP6s_example/20190128_13_34_43/suite2p/plane0/stat.npy\n",
      "no channel 2 labels found (redcell.npy)\n",
      "0\n",
      "/Users/angueyraaristjm/anaconda3/lib/python3.7/site-packages/suite2p/fig.py:134: RuntimeWarning: invalid value encountered in true_divide\n",
      "  istat = istat / (istat99-istat1)\n",
      "/Users/angueyraaristjm/anaconda3/lib/python3.7/site-packages/suite2p/fig.py:135: RuntimeWarning: invalid value encountered in minimum\n",
      "  istat = np.maximum(0, np.minimum(1, istat))\n",
      "/Users/angueyraaristjm/anaconda3/lib/python3.7/site-packages/suite2p/fig.py:135: RuntimeWarning: invalid value encountered in maximum\n",
      "  istat = np.maximum(0, np.minimum(1, istat))\n",
      "0.05141615867614746\n",
      "/Users/angueyraaristjm/anaconda3/lib/python3.7/site-packages/suite2p/fig.py:451: RuntimeWarning: invalid value encountered in true_divide\n",
      "  cc = np.dot(parent.Fbin, sn.T) / np.sqrt(np.dot(parent.Fstd,snstd))\n",
      "/Users/angueyraaristjm/anaconda3/lib/python3.7/site-packages/numpy/core/_methods.py:32: RuntimeWarning: invalid value encountered in reduce\n",
      "  return umr_minimum(a, axis, None, out, keepdims, initial)\n",
      "/Users/angueyraaristjm/anaconda3/lib/python3.7/site-packages/numpy/core/_methods.py:28: RuntimeWarning: invalid value encountered in reduce\n",
      "  return umr_maximum(a, axis, None, out, keepdims, initial)\n",
      "/Users/angueyraaristjm/anaconda3/lib/python3.7/site-packages/pyqtgraph/functions.py:869: RuntimeWarning: invalid value encountered in subtract\n",
      "  d2 = data - float(offset)\n",
      "/Users/angueyraaristjm/anaconda3/lib/python3.7/site-packages/pyqtgraph/functions.py:870: RuntimeWarning: overflow encountered in multiply\n",
      "  d2 *= scale\n",
      "svd computed in 0.00 s\n",
      "time; iteration;  explained PC variance\n",
      "0.00s     0        0.0855\n",
      "0.00s    10        0.7186\n",
      "0.00s    20        1.0000\n",
      "0.01s    30        1.0000\n",
      "0.01s    40        1.0000\n",
      "0.01s    50        1.0000\n",
      "0.01s   final      1.0000\n",
      "0.01s upsampled    1.5095\n",
      "raster map computed in 0.03 s\n",
      "svd computed in 0.00 s\n",
      "time; iteration;  explained PC variance\n",
      "0.00s     0        0.0228\n",
      "0.00s    10        0.6864\n",
      "0.00s    20        0.4896\n",
      "0.01s    30        0.9699\n",
      "0.01s    40        1.0000\n",
      "0.01s    50        1.0000\n",
      "0.01s   final      1.0000\n",
      "0.01s upsampled    1.5869\n",
      "raster map computed in 0.01 s\n",
      "svd computed in 0.00 s\n",
      "time; iteration;  explained PC variance\n",
      "0.00s     0        0.4582\n",
      "0.00s    10        0.6342\n",
      "0.00s    20        0.9492\n",
      "0.01s    30        1.0000\n",
      "0.01s    40        1.0000\n",
      "0.01s    50        1.0000\n",
      "0.01s   final      1.0000\n",
      "0.01s upsampled    1.5869\n",
      "raster map computed in 0.01 s\n",
      "/Users/angueyraaristjm/Documents/LiImaging/TwoPhoton/ChAT_gCaMP6s_example/20190128_13_34_43/suite2p/plane0/ops.npy\n",
      "playing\n",
      "paused\n",
      "===== 2019.02.21 16:02:07 =====\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/angueyraaristjm/anaconda3/lib/python3.7/site-packages/suite2p/gui.py\", line 671, in <lambda>\n",
      "    self.clicked.connect(lambda: self.press(parent, bid))\n",
      "  File \"/Users/angueyraaristjm/anaconda3/lib/python3.7/site-packages/suite2p/gui.py\", line 696, in press\n",
      "    M = fig.draw_masks(parent)\n",
      "  File \"/Users/angueyraaristjm/anaconda3/lib/python3.7/site-packages/suite2p/fig.py\", line 595, in draw_masks\n",
      "    col   = cols[n,color]\n",
      "IndexError: index 9 is out of bounds for axis 1 with size 7\n",
      "===== 2019.02.21 16:02:34 =====\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/angueyraaristjm/anaconda3/lib/python3.7/site-packages/suite2p/visualize.py\", line 147, in <lambda>\n",
      "    self.selectBtn.clicked.connect(lambda: self.select_cells(parent))\n",
      "  File \"/Users/angueyraaristjm/anaconda3/lib/python3.7/site-packages/suite2p/visualize.py\", line 364, in select_cells\n",
      "    M = fig.draw_masks(parent)\n",
      "  File \"/Users/angueyraaristjm/anaconda3/lib/python3.7/site-packages/suite2p/fig.py\", line 595, in draw_masks\n",
      "    col   = cols[n,color]\n",
      "IndexError: index 9 is out of bounds for axis 1 with size 7\n",
      "===== 2019.02.21 16:02:35 =====\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/angueyraaristjm/anaconda3/lib/python3.7/site-packages/suite2p/visualize.py\", line 147, in <lambda>\n",
      "    self.selectBtn.clicked.connect(lambda: self.select_cells(parent))\n",
      "  File \"/Users/angueyraaristjm/anaconda3/lib/python3.7/site-packages/suite2p/visualize.py\", line 364, in select_cells\n",
      "    M = fig.draw_masks(parent)\n",
      "  File \"/Users/angueyraaristjm/anaconda3/lib/python3.7/site-packages/suite2p/fig.py\", line 595, in draw_masks\n",
      "    col   = cols[n,color]\n",
      "IndexError: index 9 is out of bounds for axis 1 with size 7\n",
      "===== 2019.02.21 16:02:36 =====\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/angueyraaristjm/anaconda3/lib/python3.7/site-packages/suite2p/visualize.py\", line 147, in <lambda>\n",
      "    self.selectBtn.clicked.connect(lambda: self.select_cells(parent))\n",
      "  File \"/Users/angueyraaristjm/anaconda3/lib/python3.7/site-packages/suite2p/visualize.py\", line 364, in select_cells\n",
      "    M = fig.draw_masks(parent)\n",
      "  File \"/Users/angueyraaristjm/anaconda3/lib/python3.7/site-packages/suite2p/fig.py\", line 595, in draw_masks\n",
      "    col   = cols[n,color]\n",
      "IndexError: index 9 is out of bounds for axis 1 with size 7\n",
      "===== 2019.02.21 16:02:42 =====\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/angueyraaristjm/anaconda3/lib/python3.7/site-packages/suite2p/gui2p.py\", line 1056, in plot_clicked\n",
      "    M = fig.draw_masks(self)\n",
      "  File \"/Users/angueyraaristjm/anaconda3/lib/python3.7/site-packages/suite2p/fig.py\", line 595, in draw_masks\n",
      "    col   = cols[n,color]\n",
      "IndexError: index 9 is out of bounds for axis 1 with size 7\n",
      "===== 2019.02.21 16:02:43 =====\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/angueyraaristjm/anaconda3/lib/python3.7/site-packages/suite2p/gui2p.py\", line 1056, in plot_clicked\n",
      "    M = fig.draw_masks(self)\n",
      "  File \"/Users/angueyraaristjm/anaconda3/lib/python3.7/site-packages/suite2p/fig.py\", line 595, in draw_masks\n",
      "    col   = cols[n,color]\n",
      "IndexError: index 9 is out of bounds for axis 1 with size 7\n"
     ]
    }
   ],
   "source": [
    "!python -m suite2p"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [],
   "source": []
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "Python 3",
   "language": "python",
   "name": "python3"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.7.1"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 2
}
